server:
  port: 8091
spring:
  application:
    name: sentinel-service
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
management:
 endpoints:
  web:
   exposure:
    include: '*'